{{- if .Values.registry.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: beeai-platform-registry-secret
  labels:
    app: beeai-platform-registry
    {{- include "beeai-platform.labels" . | nindent 4 }}
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ printf "{\"auths\":{\"%s:%d\":{\"auth\":\"\",\"username\":\"\",\"password\":\"\"}}}" "beeai-platform-registry-svc" (.Values.registry.service.port | int) | b64enc }}
{{- end }}