"""Add procrastinate initial migrations

Revision ID: 638be28ea3f9
Revises: be5ec6ff3271
Create Date: 2025-06-19 13:58:36.996259

"""

import sqlparse
from pathlib import Path
from typing import Sequence, Union

from alembic import op

from beeai_server import get_configuration

# revision identifiers, used by Alembic.
revision: str = "638be28ea3f9"
down_revision: Union[str, None] = "be5ec6ff3271"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    procrastinate_schema = get_configuration().persistence.procrastinate_schema
    op.execute(f"CREATE SCHEMA IF NOT EXISTS {procrastinate_schema}")
    op.execute(f"SET search_path TO {procrastinate_schema}")
    with open(Path(__file__).parent / "procrastinate.sql") as f:
        for statement in sqlparse.split(f.read()):
            op.execute(statement)
    op.execute("SET search_path TO public")


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(f"DROP SCHEMA IF EXISTS {get_configuration().persistence.procrastinate_schema}")
