from typing import Protocol

from a2a.types import AgentExtension, Artifact, Message

from beeai_sdk.server.dependencies import Depends


class ContextStoreInstance(Protocol):
    def __init__(self, context_id: str, *args, **kwargs): ...
    async def load_history(self) -> list[Message | Artifact]: ...
    async def store(self, data: Message | Artifact) -> None: ...
    async def store_metadata_value(self, key: str, value: str): ...
    async def get_metadata_value(self, key: str) -> str | None: ...


class ContextStore(Protocol):
    def modify_extensions(self, extensions: list[AgentExtension]) -> list[AgentExtension]: ...
    async def create(
        self, context_id: str, dependencies: list[Depends]
    ) -> tuple[ContextStoreInstance, list[Depends]]: ...
